package mesh

import "encoding/json"

// v0.1 uses JSON for the bus envelope: inspectable and dependency-free. The
// frozen wire schema (proto/CBOR) is regenerated by lane D; the fabric only
// needs a stable key+payload framing here.

func marshalEnvelope(e envelope) ([]byte, error) { return json.Marshal(e) }

func unmarshalEnvelope(b []byte, e *envelope) error { return json.Unmarshal(b, e) }
