package mesh

// compute.go adds a minimal, capability-gated request/response for compute
// dispatch over a point-to-point libp2p/QUIC stream. It is the mesh-transport
// realization of Vertical 03's control-plane task dispatch: a requester sends a
// contract.ComputeTask to a worker, the worker authorizes the presented
// capability and runs the task, and the result bytes come back over the same
// stream.
//
// What is REAL here:
//   - The transport is the existing libp2p host over QUIC (quic-v1): encrypted,
//     multiplexed, PeerID-authenticated by the QUIC/TLS handshake. We reuse the
//     same streamSession framing (4-byte length prefix) as the generic session.
//   - The capability is verified by the worker's CapKernel BEFORE any work runs
//     (no ambient authority: an unauthorized task is rejected with the kernel's
//     error). The cap handle travels in-band only because, in v0.1, both nodes
//     share one logical kernel namespace in the demo; the seam is the same one a
//     CapTP frame would use.
//
// What is a STUB / not yet here (not faked):
//   - Promise pipelining (CapTP) across multiple shards is engine-side in Rust
//     (core/runtime, Phase E2); this path carries a single task to completion.
//   - The cap handle is an opaque u64 in the demo's shared-kernel model; a
//     cross-kernel signed-capability transfer (CBOR cap in ComputeTask.Caps,
//     verified against the issuer key) is the hardening step noted in HANDOFF.md.

import (
	"context"
	"encoding/json"
	"fmt"

	contract "github.com/hash066/cerberus/contract/go"
	"github.com/libp2p/go-libp2p/core/network"
)

// computeProto is the libp2p protocol id for capability-gated compute dispatch.
const computeProto = "/cerberus/compute/1.0.0"

// ComputeHandler runs a dispatched task on the worker side. It is given the task
// and the in-band capability handle the requester presented; the implementation
// is responsible for authorizing that capability (it owns the CapKernel that
// minted it) and for resolving the task's component CID to bytes before running.
//
// Returning a contract.ComputeResult with OK=false (or an error) both report
// failure; an error additionally aborts the stream. The result is sent back to
// the requester verbatim.
type ComputeHandler func(ctx context.Context, task contract.ComputeTask, capH contract.CapHandle) (contract.ComputeResult, error)

// computeRequest is the on-wire request frame: a ComputeTask plus the capability
// handle that authorizes its execution. JSON keeps it inspectable and
// dependency-free (the frozen CBOR/proto wire form is regenerated by lane D).
type computeRequest struct {
	Task computeTaskWire    `json:"task"`
	Cap  contract.CapHandle `json:"cap"`
}

// computeTaskWire is the JSON projection of contract.ComputeTask. We project
// explicitly rather than tagging the frozen contract struct so the contract is
// not edited from this lane.
type computeTaskWire struct {
	TaskID    []byte   `json:"task_id"`
	Component []byte   `json:"component"` // IPLD CID bytes of the WASM component
	Caps      [][]byte `json:"caps,omitempty"`
	ResultCap []byte   `json:"result_cap,omitempty"`
}

func taskToWire(t contract.ComputeTask) computeTaskWire {
	return computeTaskWire{TaskID: t.TaskID, Component: t.Component, Caps: t.Caps, ResultCap: t.ResultCap}
}

func (w computeTaskWire) toTask() contract.ComputeTask {
	return contract.ComputeTask{TaskID: w.TaskID, Component: w.Component, Caps: w.Caps, ResultCap: w.ResultCap}
}

// computeResponse is the on-wire result frame.
type computeResponse struct {
	TaskID []byte `json:"task_id"`
	OK     bool   `json:"ok"`
	Output []byte `json:"output,omitempty"`
	Error  string `json:"error,omitempty"`
}

// ServeCompute registers the worker-side handler for compute dispatch. It must
// be called once, before remote requests arrive. The handler runs on a fresh
// goroutine per inbound stream.
func (f *Fabric) ServeCompute(h ComputeHandler) {
	f.host.SetStreamHandler(computeProto, func(s network.Stream) {
		f.handleComputeStream(s, h)
	})
}

func (f *Fabric) handleComputeStream(s network.Stream, h ComputeHandler) {
	ss := newStreamSession(s)
	defer ss.Close()

	raw, err := ss.Recv()
	if err != nil {
		_ = s.Reset()
		return
	}
	var req computeRequest
	if err := json.Unmarshal(raw, &req); err != nil {
		_ = writeComputeError(ss, nil, fmt.Sprintf("decode request: %v", err))
		return
	}

	res, herr := h(f.ctx, req.Task.toTask(), req.Cap)
	if herr != nil {
		_ = writeComputeError(ss, req.Task.TaskID, herr.Error())
		return
	}
	_ = ss.Send(mustMarshalComputeResponse(computeResponse{
		TaskID: res.TaskID,
		OK:     res.OK,
		Output: res.Output,
		Error:  res.Error,
	}))
}

// RequestCompute dials a worker by its Ed25519 PeerID, sends the task and the
// authorizing capability over a QUIC stream, and returns the worker's result.
// The worker authorizes the capability before running anything.
func (f *Fabric) RequestCompute(ctx context.Context, worker contract.PeerID, task contract.ComputeTask, capH contract.CapHandle) (contract.ComputeResult, error) {
	pid, err := toLibp2pID(worker)
	if err != nil {
		return contract.ComputeResult{}, err
	}
	s, err := f.host.NewStream(ctx, pid, computeProto)
	if err != nil {
		return contract.ComputeResult{}, contract.Errf(contract.ErrPartitioned, err.Error())
	}
	ss := newStreamSession(s)
	defer ss.Close()

	body, err := json.Marshal(computeRequest{Task: taskToWire(task), Cap: capH})
	if err != nil {
		return contract.ComputeResult{}, err
	}
	if err := ss.Send(body); err != nil {
		return contract.ComputeResult{}, contract.Errf(contract.ErrPartitioned, err.Error())
	}

	raw, err := ss.Recv()
	if err != nil {
		return contract.ComputeResult{}, err
	}
	var resp computeResponse
	if err := json.Unmarshal(raw, &resp); err != nil {
		return contract.ComputeResult{}, fmt.Errorf("mesh: decode compute response: %w", err)
	}
	return contract.ComputeResult{
		TaskID: resp.TaskID,
		OK:     resp.OK,
		Output: resp.Output,
		Error:  resp.Error,
	}, nil
}

func writeComputeError(ss *streamSession, taskID []byte, msg string) error {
	return ss.Send(mustMarshalComputeResponse(computeResponse{TaskID: taskID, OK: false, Error: msg}))
}

func mustMarshalComputeResponse(r computeResponse) []byte {
	b, err := json.Marshal(r)
	if err != nil {
		// computeResponse only contains JSON-safe types; marshal cannot fail.
		b, _ = json.Marshal(computeResponse{OK: false, Error: "internal: marshal response"})
	}
	return b
}
