package telemetry

import (
	"encoding/json"

	contract "github.com/hash066/cerberus/contract/go"
)

// encode/decode serialize NodeTelemetry for the bus. v0.1 uses JSON; the frozen
// proto wire form (telemetry.proto) is generated by lane D and swapped in at
// integration without changing this package's seam.

func encode(t contract.NodeTelemetry) ([]byte, error) { return json.Marshal(t) }

// Decode parses a telemetry payload (exported for consumers/tests).
func Decode(b []byte) (contract.NodeTelemetry, error) {
	var t contract.NodeTelemetry
	err := json.Unmarshal(b, &t)
	return t, err
}
